/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baralho;

import javax.swing.ImageIcon;

/**
 *
 * @author diego
 */
public class Jogo extends javax.swing.JFrame {
    CartaBaralho carta_jogador_baralho [] = CartaBaralho.gera_baralho();
    CartaBaralho carta_mesa_baralho [] = CartaBaralho.gera_baralho();
    int soma_casa = 0;
    int soma_jogador = 0;
    
    
    
    public Jogo() {
        initComponents();
    }
    public void chama_carta() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_mesa_baralho[0].getNaipe().getNome_naipe()+ carta_mesa_baralho[0].getCarta().getNome_carta_imagem()+".png"));
        carta_mesa_01.setIcon(imagem_carta);
        
        
    }
    public void chama_carta2() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_mesa_baralho[1].getNaipe().getNome_naipe()+ carta_mesa_baralho[1].getCarta().getNome_carta_imagem()+".png"));
        carta_mesa_02.setIcon(imagem_carta);
        
        
    }
    public void chama_carta3() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_mesa_baralho[2].getNaipe().getNome_naipe()+ carta_mesa_baralho[2].getCarta().getNome_carta_imagem()+".png"));
        carta_mesa_03.setIcon(imagem_carta);
        
        
    }
    public void chama_carta4() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_mesa_baralho[3].getNaipe().getNome_naipe()+ carta_mesa_baralho[3].getCarta().getNome_carta_imagem()+".png"));
        carta_mesa_04.setIcon(imagem_carta);
        
        
    }
    public void chama_carta5() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_mesa_baralho[4].getNaipe().getNome_naipe()+ carta_mesa_baralho[4].getCarta().getNome_carta_imagem()+".png"));
        carta_mesa_05.setIcon(imagem_carta);
        
        
    }
    public void chama_carta6() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_jogador_baralho[0].getNaipe().getNome_naipe()+ carta_jogador_baralho[0].getCarta().getNome_carta_imagem()+".png"));
        carta_jogador_01.setIcon(imagem_carta);
        
        
    }
    public void chama_carta7() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_jogador_baralho[1].getNaipe().getNome_naipe()+ carta_jogador_baralho[1].getCarta().getNome_carta_imagem()+".png"));
        carta_jogador_02.setIcon(imagem_carta);
        
        
    }
    public void chama_carta8() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_jogador_baralho[2].getNaipe().getNome_naipe()+ carta_jogador_baralho[2].getCarta().getNome_carta_imagem()+".png"));
        carta_jogador_03.setIcon(imagem_carta);
        
        
    }
    public void chama_carta9() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_jogador_baralho[3].getNaipe().getNome_naipe()+ carta_jogador_baralho[3].getCarta().getNome_carta_imagem()+".png"));
        carta_jogador_04.setIcon(imagem_carta);
        
        
    }
    public void chama_carta10() {
        ImageIcon imagem_carta = new ImageIcon(getClass().getResource("..\\baralho_cartas\\"+carta_jogador_baralho[4].getNaipe().getNome_naipe()+ carta_jogador_baralho[4].getCarta().getNome_carta_imagem()+".png"));
        carta_jogador_05.setIcon(imagem_carta);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botão_carta_mesa01 = new javax.swing.JButton();
        botão_carta_mesa02 = new javax.swing.JButton();
        botão_carta_mesa03 = new javax.swing.JButton();
        botão_carta_mesa04 = new javax.swing.JButton();
        botão_carta_mesa05 = new javax.swing.JButton();
        botão_carta_jogador01 = new javax.swing.JButton();
        botão_carta_jogador02 = new javax.swing.JButton();
        botão_carta_jogador03 = new javax.swing.JButton();
        botão_carta_jogador04 = new javax.swing.JButton();
        botão_carta_jogador05 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        carta_jogador_04 = new javax.swing.JLabel();
        carta_jogador_03 = new javax.swing.JLabel();
        carta_jogador_01 = new javax.swing.JLabel();
        carta_jogador_02 = new javax.swing.JLabel();
        carta_mesa_01 = new javax.swing.JLabel();
        carta_mesa_02 = new javax.swing.JLabel();
        carta_mesa_03 = new javax.swing.JLabel();
        carta_mesa_04 = new javax.swing.JLabel();
        carta_mesa_05 = new javax.swing.JLabel();
        carta_jogador_05 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botão_carta_mesa01.setText("jButton1");
        botão_carta_mesa01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_mesa01ActionPerformed(evt);
            }
        });

        botão_carta_mesa02.setText("jButton2");
        botão_carta_mesa02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_mesa02ActionPerformed(evt);
            }
        });

        botão_carta_mesa03.setText("jButton3");
        botão_carta_mesa03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_mesa03ActionPerformed(evt);
            }
        });

        botão_carta_mesa04.setText("jButton4");
        botão_carta_mesa04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_mesa04ActionPerformed(evt);
            }
        });

        botão_carta_mesa05.setText("jButton5");
        botão_carta_mesa05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_mesa05ActionPerformed(evt);
            }
        });

        botão_carta_jogador01.setText("jButton6");
        botão_carta_jogador01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_jogador01ActionPerformed(evt);
            }
        });

        botão_carta_jogador02.setText("jButton7");
        botão_carta_jogador02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_jogador02ActionPerformed(evt);
            }
        });

        botão_carta_jogador03.setText("jButton8");
        botão_carta_jogador03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_jogador03ActionPerformed(evt);
            }
        });

        botão_carta_jogador04.setText("jButton9");
        botão_carta_jogador04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_jogador04ActionPerformed(evt);
            }
        });

        botão_carta_jogador05.setText("jButton10");
        botão_carta_jogador05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_carta_jogador05ActionPerformed(evt);
            }
        });

        jTextField1.setText("          CARTAS CASA");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("    CARTAS JOGADOR");

        carta_jogador_04.setText("jLabel2");

        carta_jogador_03.setText("jLabel2");

        carta_jogador_01.setText("jLabel2");

        carta_jogador_02.setText("jLabel2");

        carta_mesa_01.setText("jLabel2");

        carta_mesa_02.setText("jLabel2");

        carta_mesa_03.setText("jLabel2");

        carta_mesa_04.setText("jLabel2");

        carta_mesa_05.setText("jLabel2");

        carta_jogador_05.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botão_carta_mesa01)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(carta_jogador_01, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botão_carta_jogador01))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botão_carta_mesa02)
                                    .addComponent(botão_carta_jogador02))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botão_carta_mesa03)
                                    .addComponent(botão_carta_jogador03)
                                    .addComponent(carta_mesa_03, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(carta_jogador_02, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(carta_jogador_03, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carta_mesa_01, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_mesa_02, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botão_carta_mesa04)
                    .addComponent(botão_carta_jogador04)
                    .addComponent(carta_jogador_04, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_mesa_04, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botão_carta_mesa05)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carta_mesa_05, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botão_carta_jogador05))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(carta_jogador_05, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botão_carta_mesa01)
                    .addComponent(botão_carta_mesa02)
                    .addComponent(botão_carta_mesa03)
                    .addComponent(botão_carta_mesa04)
                    .addComponent(botão_carta_mesa05)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carta_mesa_01, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_mesa_02, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_mesa_03, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_mesa_04, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_mesa_05, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botão_carta_jogador01)
                    .addComponent(botão_carta_jogador02)
                    .addComponent(botão_carta_jogador03)
                    .addComponent(botão_carta_jogador04)
                    .addComponent(botão_carta_jogador05))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carta_jogador_01, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carta_jogador_02, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carta_jogador_03, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carta_jogador_04, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carta_jogador_05, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botão_carta_mesa05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_mesa05ActionPerformed
    chama_carta5();
    }//GEN-LAST:event_botão_carta_mesa05ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void botão_carta_mesa01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_mesa01ActionPerformed
        chama_carta();
    }//GEN-LAST:event_botão_carta_mesa01ActionPerformed

    private void botão_carta_mesa02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_mesa02ActionPerformed
        chama_carta2();
    }//GEN-LAST:event_botão_carta_mesa02ActionPerformed

    private void botão_carta_mesa03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_mesa03ActionPerformed
    chama_carta3();
    }//GEN-LAST:event_botão_carta_mesa03ActionPerformed

    private void botão_carta_mesa04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_mesa04ActionPerformed
    chama_carta4();
    }//GEN-LAST:event_botão_carta_mesa04ActionPerformed

    private void botão_carta_jogador01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_jogador01ActionPerformed
    chama_carta6();        // TODO add your handling code here:
    }//GEN-LAST:event_botão_carta_jogador01ActionPerformed

    private void botão_carta_jogador02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_jogador02ActionPerformed
    chama_carta7();
    }//GEN-LAST:event_botão_carta_jogador02ActionPerformed

    private void botão_carta_jogador03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_jogador03ActionPerformed
    chama_carta8();
    }//GEN-LAST:event_botão_carta_jogador03ActionPerformed

    private void botão_carta_jogador04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_jogador04ActionPerformed
    chama_carta9();
    }//GEN-LAST:event_botão_carta_jogador04ActionPerformed

    private void botão_carta_jogador05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_carta_jogador05ActionPerformed
    chama_carta10();
    }//GEN-LAST:event_botão_carta_jogador05ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botão_carta_jogador01;
    private javax.swing.JButton botão_carta_jogador02;
    private javax.swing.JButton botão_carta_jogador03;
    private javax.swing.JButton botão_carta_jogador04;
    private javax.swing.JButton botão_carta_jogador05;
    private javax.swing.JButton botão_carta_mesa01;
    private javax.swing.JButton botão_carta_mesa02;
    private javax.swing.JButton botão_carta_mesa03;
    private javax.swing.JButton botão_carta_mesa04;
    private javax.swing.JButton botão_carta_mesa05;
    private javax.swing.JLabel carta_jogador_01;
    private javax.swing.JLabel carta_jogador_02;
    private javax.swing.JLabel carta_jogador_03;
    private javax.swing.JLabel carta_jogador_04;
    private javax.swing.JLabel carta_jogador_05;
    private javax.swing.JLabel carta_mesa_01;
    private javax.swing.JLabel carta_mesa_02;
    private javax.swing.JLabel carta_mesa_03;
    private javax.swing.JLabel carta_mesa_04;
    private javax.swing.JLabel carta_mesa_05;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
